version: '2'
services:
  microservice:
    build: .
    image: "learning:1.0.4"
    environment:
    - PORT=9090
    ports:
    - "9090:9090"
  nginx:
    image: "nginx"
    ports:
    - "8080:80"
    links:
    - microservice