apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-api-example
  labels:
    app: go-api-example
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: go-api-example
        tier: service
    spec:
      containers:
      - name: go-api-example
        image: "go-api-example:1.0.1"
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5