apiVersion: v1
kind: Pod
metadata:
  name: go-api-example
  labels:
    language: go
    env: test
spec:
  containers:
  - name: go-api-example
    image: go-api-example:1.0.1
    ports:
    - containerPort: 8080
      protocol: TCP